@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

RevisionTool *-right-> "1" UniqueAnswerableList
RevisionTool *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueAnswerableList
UniqueTagList -[hidden]down- UniqueAnswerableList

UniqueTagList *-right-> "*" Tag
UniqueAnswerableList o-right-> Answerable

Answerable o-up-> "*" Tag

Answerable *--> Name
Answerable *--> Phone
Answerable *--> Email
Answerable *--> Address
@enduml
